Feat 48/create migration
vention-js-lab/ventioners-stayhub-backend pull request #37
Opened 2024-12-01 14:24 UTC by AKILBEK-UR

in order to test locally you should download pgAdmin extension postgis

2024-12-02 09:51 UTC, farrooh requested changes

2024-12-02 09:51 UTC, farrooh commented on src/modules/accommodations/accommodations.service.ts
> +      };
Create a function that returns this object since it's used more than once.

2024-12-02 09:51 UTC, farrooh commented on src/modules/accommodations/entities/accommodation.entity.ts
> +  locationCoordinates: { type: 'Point'; coordinates: [number, number] };
Create a type for this

2024-12-06 12:14 UTC, purple-mountain approved these changes

2024-12-06 12:14 UTC, purple-mountain commented on src/shared/util/createCordinates.ts
> +// src/types/point-geometry.type.ts
don't forget to remove this

2024-12-06 12:37 UTC, farrooh approved these changes

2024-12-06 13:57 UTC, merged