feat-57/payment integration completed
vention-js-lab/ventioners-stayhub-backend pull request #41
Opened 2024-12-05 07:56 UTC by bek-shoyatbek

- [x] Creating new checkout sesssion with Accommodation details ( name, description, image , and price) 

- [x] Handeling payment events ( succeeded, failed )

2024-12-05 12:26 UTC, farrooh requested changes
It's better to not name the files, modules, and endpoint routes after the service's name (Stripe). You might want to intagrate some other payment service in the future; then it will require a lot of renaming. The best approach is to create a different service provider for Stripe and then use/call it in the payments service. This way you can add more payment integration, and there will be a unified endpoint for all of them:
PaymentsController > PaymentsService > [StripeService, ClickService, etc.]

2024-12-05 12:26 UTC, farrooh commented on .env.example
> +STRIPE_WEBHOOK_SECRET=whsec_a81cf3
Let's do not include test keys here

2024-12-05 12:26 UTC, farrooh commented on src/main.ts
> +  const app = await NestFactory.create(AppModule, { rawBody: true });
Please only enable rawBody at the endpoints where it is necessary.

2024-12-05 12:26 UTC, farrooh commented on src/modules/stripe/constants/stripe-secret-key.constant.ts
> +export const STRIPE_SECRET_KEY = 'STRIPE_SECRET_KEY';
Why do we need this?

2024-12-05 12:26 UTC, farrooh commented on src/modules/stripe/stripe.controller.ts
> +  ) {
Validate the existence of signature.

2024-12-05 12:26 UTC, farrooh commented on src/modules/stripe/stripe.module.ts
> +  exports: [StripeService],
Why export the service?

2024-12-05 12:26 UTC, farrooh commented on src/modules/stripe/stripe.module.ts
> +@Global()
Any reason to make it global?

2024-12-05 12:26 UTC, farrooh commented on src/modules/stripe/stripe.controller.ts
> +export class StripeController {
Let's name this PaymentService. And we should rename other components like module and service names to not be stuck to the service name (Stripe) as well.

2024-12-05 12:26 UTC, farrooh commented on src/modules/stripe/stripe.controller.ts
> +@Controller('stripe')
We should call this route `payment` instead.

2024-12-05 12:26 UTC, farrooh commented on src/modules/stripe/stripe.controller.ts
> +  @HttpCode(200)
You forgot to add guards

2024-12-05 14:16 UTC, farrooh requested changes

2024-12-05 14:16 UTC, farrooh commented on src/modules/stripe/stripe.service.ts
> +    }
Maybe booking exists but it doesn't belong to the user? It would be better to check that case as well and send a proper message.

2024-12-05 14:16 UTC, farrooh commented on src/modules/stripe/stripe.service.ts
> +      console.log(error);
Use Nest.js Logger

2024-12-05 18:57 UTC, purple-mountain commented on src/shared/helpers/generate-after-payment-url.ts
can you put all of utils inside helpers? or you can move all helpers inside utils...
right now there is duplication

2024-12-05 18:57 UTC, purple-mountain commented on src/modules/stripe/stripe.service.ts
> +    if (booking.user.id !== userId) {
doesn't getBooking already have this check?

2024-12-05 18:57 UTC, purple-mountain commented on src/modules/stripe/stripe.service.ts
> +    if (!booking) {
this is also present in getBooking

2024-12-05 18:57 UTC, purple-mountain commented on src/modules/stripe/stripe.service.ts
> +            : BookingStatus.CANCELLED,
does this mean that if payment fails booking will be cancelled ?

2024-12-05 20:15 UTC, purple-mountain commented on src/modules/stripe/stripe.service.ts
> +            : BookingStatus.CANCELLED,
can the user redo their payment after failure or do they have to create a new booking again?

2024-12-06 08:17 UTC, purple-mountain approved these changes

2024-12-06 11:34 UTC, purple-mountain commented
in my merged pr, I updated a little bit the "buildMinioFileUrl" function that you renamed to "generatePublicFileUrl". When you resolve conflicts, make sure that it uses my updated function otherwise production will be affected.

2024-12-07 18:24 UTC, purple-mountain commented on .env.example
> +STRIPE_SECRET_KEY=sk_test_51QS0nQ
real values or just example

2024-12-07 18:24 UTC, purple-mountain commented on src/database/database.module.ts
> +          Payment,
duplication?

2024-12-07 18:24 UTC, purple-mountain commented on src/modules/payments/payments.controller.ts
> +  @HttpCode(200)
I think no need for this. Default is 200 if I am not mistaken

2024-12-07 18:24 UTC, purple-mountain commented on src/modules/stripe/stripe.service.ts
> +      // For now we redirect to the same page with query params
dont forget to remove it

2024-12-10 12:01 UTC, farrooh approved these changes

2024-12-11 07:24 UTC, merged