Created login
vention-js-lab/ventioners-stayhub-backend pull request #6
Opened 2024-11-10 13:53 UTC by AKILBEK-UR

2024-11-10 14:25 UTC, purple-mountain commented on src/modules/auth/auth.module.ts
>    imports: [
I think we do not have AUTH_TOKEN_SECRET or AUTH_TOKEN_EXPIRES_IN env variables. You should change those names to AUTH_ACCESS_TOKEN_SECRET or AUTH_ACCESS_TOKEN_EXPIRES_IN

2024-11-10 14:27 UTC, purple-mountain commented on src/modules/auth/auth.service.ts
>        secret: this.configService.get('AUTH_ACCESS_TOKEN_SECRET'),
After providing expiresIn and secret options inside auth.module.ts during import, you can omit options and just use 
```js
    const accessToken = await this.jwtService.signAsync(payload);
```
when you are creating access tokens.

2024-11-10 15:01 UTC, purple-mountain requested changes
Later, we will also need to add refresh tokens and cookies, but for now I think it is good enough.

2024-11-11 06:02 UTC, mukhammadjon-ss approved these changes
After resolving comments you can merge it.

2024-11-11 09:26 UTC, msirojiddinov approved these changes

2024-11-11 09:27 UTC, purple-mountain approved these changes

2024-11-11 09:36 UTC, merged